### ISSUE TITLE
Big Issue with login username

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/DNN.ActiveDirectory#24]
I installed the 6.0.2 Now no matter what the user logins as the AD module creates a new account.
I've managed to create an account using the below logins:
1) test\username
2) anything.com\username
3) username@mywebsite.com

After these three I gave up trying. ALL THREE ATTEMPTS create new accounts !!!

**Comment by sawest** [comment]
Please be more specific about what issue you are having.  The AD module is supposed to create accounts if set to in settings.

Note:  You are using 3 different domains.  If you set the default domain in settings you do not need to add the domain in the username at all.  User accounts are created with the domain included so if you use different domains in the username then a new user should be created because that user does not exist.

**Comment by muddeatr** [comment]
If a user types in "test\joebagadonutz" as a username then the AD module create the user "test\joebagadonutz". The domain "test" in this instance is NOT valid but the user is and the module creates the user. So not only does the module create this user but the user already existed under the real domain "domain\joebagadonutz".

Does this help? Let me get to my test machine and I can give you more scenarios.

**Comment by muddeatr** [comment]
Ok so lets start with a NEW user. Never logged in yet.

The user logged in:
username: joebags
password: test123

The user is validated and created. All as expected !!!
-----------------------------------------------------------
Now that same user logins again:
username: joebags@somewhere.com
password: test123

Another Account is created as "somewhere.com\joebags"
This is WRONG!!!
-------------------------------------------------------------
Now that same user logins again:
username: letsplay\joebags
password: test123

Yet another account is created as "letsplay\joebags"
This is WRONG!!!
--------------------------------------------------------------
Not only are ALL these logins wrong but they are all wrong because "somewhere.com" is NOT a valid email for this account and "letsplay" is NOT a valid Domain either.

**Comment by muddeatr** [comment]
"You are using 3 different domains. If you set the default domain in settings you do not need to add the domain in the username at all. User accounts are created with the domain included so if you use different domains in the username then a new user should be created because that user does not exist."

None of the 3 domains I used are valid how can you create an account with an invalid AD domain???
I can't stop 1500 users from not typing in an email instead of their username. The module should validate exactly what the user types in.

**Comment by muddeatr** [comment]
Out of ALL of these bogus accounts that were created NONE of them were created with the "Default Domain" as part of the username. The only account created correctly with the default domain was the first account where the user typed in just his username. This is why the module should only compare exactly what the user types in the username field.

**Comment by sawest** [comment]
Thanks for the extra information.  It is helpful.

If a default domain is set in settings, the domain used in the username (regardless of invalid domain) is stripped and the default is used in its place.  This is why authentication works in each scenario.

However, the full username is used to for searching and creating the local DNN account.  This does appear to be bug that could be improved upon.  

A good test to help verify this issue would be for you to take out the default domain, repeat the same test, and post your results.  I expect that none of the users with an invalid domain will be able to authenticate.

**Comment by muddeatr** [comment]
OK, Gimme a few minutes.

**Comment by muddeatr** [comment]
I removed the default domain from the settings and here are the results. Unfortunately 2 for 3 wrong :-(

-----------------------------------------------------------------------------------
User 1
The user logged in:
username: some\joebags
password: test123
The AD Module created a username of "some\joebags"  --- This is WRONG joebags is a valid user but "some" is NOT a valid domain
---------------------------------------------------------------------------------------------------------------
User 2
Now that same user logins again:
username: joebags@somewhere.com
password: test123

The User receives and Error: "Login Failed. Please remember that passwords are case sensitive. "
This I believe is correct.
---------------------------------------------------------------------------------------------------------------
User 3
The user logged in:
username: joebags
password: test123

The AD Module errors out in the Event Log.
Page Load Exception
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:b9006fde-d64d-41d4-99f7-d23f1224cd84
AssemblyVersion:8.0.3
PortalId:1
UserId:-1
TabId:82
RawUrl:/Login?returnurl=%2f
Referrer:https://www.mywebsite.com/Login?returnurl=%2f
UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
ExceptionHash:knvEgsWmgzlm37RTL4BLpg==
Message:Index was outside the bounds of the array.
StackTrace:
InnerMessage:Index was outside the bounds of the array.
InnerStackTrace:
   at DotNetNuke.Authentication.ActiveDirectory.Login.cmdLogin_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**Comment by muddeatr** [comment]
The 1st fix for me was the login.ascx.vb file. 

I reverted the current 6.0.2 code back to 5.0.3 which work fine for people attempting to use an email address as a login.

The current block near line 118
                        If strDomain.Contains(sDefaultDomain) Then
                            theUser = Trim(sDefaultDomain).Replace("\", "") & "\" & theUser
                        Else
                            theUser = strDomain & "\" & theUser
                        End If

was changed to:
                        If strDomain.Contains(sDefaultDomain) Then
                            theUser = Trim(sDefaultDomain).Replace("\", "") & "\" & theUser
                        Else
                            theUser = txtUsername.Text
                        End If

**Comment by muddeatr** [comment]
The 2nd fix and the most important was found in the IsAuthenticated function in the ADSIProvider.vb file. Near line 92 the DirectoryEntry call had a parameter commented out in 6.0.2 that worked fine in 5.0.3 so I uncommented the call and so far everything seems to be working fine and as expected. Although I will be testing more thoroughly tomorrow.

This
Dim userEntry As New DirectoryEntry (Path, UserName, Password)

was changed back to the way it was previously.
Dim userEntry As New DirectoryEntry (Path, UserName, Password, AuthenticationTypes.Signing)

**Comment by sawest** [comment]
Great!  Please initiate a pull request when you get ready.  Thanks!

**Comment by muddeatr** [comment]
I'd love to help out in that regards but I have no idea how to use GitHub for versioning control. Plus my method of debugging and fixing this issue is probably a bit unorthodox.

**Comment by muddeatr** [comment]
I can't even find a way of contacting you privately on this website! LOL!!!

**Comment by sawest** [comment]
That's too bad.  Always need more help.

Did you recompile the module after you made the changes?  Simply changing the .vb files alone won't actually change anything in the .dll used by the DNN instance.  Just making sure as you seem to be new at this as per your last statement.

Thanks for working on it.

**Comment by muddeatr** [comment]
I downloaded the source code made the two changes above rebuilt the project, then replaced the dll on my test machine with the new compiled dll.

I'm new to github and DNN. I've been programming windows applications for 15 years.

**Comment by sawest** [comment]
@muddeatr I went to make these code changes for you and the first change was already made.  I then downloaded the source code from github for 6.0.0 and 6.0.2 and the change is already there.  I think you must have been looking at/changing the wrong file or something.  Can you please verify?

Which install package have you been using to do testing with?

**Comment by sawest** [comment]
I think I may have misunderstood your comment.  Did you change the code BACK to theUser = txtUsername.Text for fix or are saying that 6.0.2 included the code change theUser = txtUsername.Text?

**Comment by muddeatr** [comment]
I used the 6.0.2 source code zip file. 
Yes my fixes were.
1) changing the code BACK to "theUser = txtUsername.Text" in the login.ascx.vb file
2) uncomment the "AuthenticationTypes.Signing" in the ADSIProvider.vb file. Changing the code BACK to Dim userEntry As New DirectoryEntry (Path, UserName, Password, AuthenticationTypes.Signing)

**Comment by muddeatr** [comment]
Part of my reasoning for not being able to do the pull request is because I have a Visual Studio 2017 environment and opening up the solution from this source code wasn't a straight up click event :-)

I also tried to build the package as a "Release" to build the install package but the throws a bunch of errors also. If you could make those two changes and create an install for me that would be great. I can then try to run the install on my test machine to do further testing.

**Comment by sawest** [comment]
#12 duplicate

**Comment by sawest** [comment]
There was a little more causing issues then what appeared on the surface.  I ended up changing a code differently than you showed above.

Pull request coming shortly.

**Comment by sawest** [comment]
#27 pull request fixed

**Comment by muddeatr** [comment]
@sawest That sounds great. I'll get it on my test box tomorrow.

**Comment by sawest** [comment]
Ready to close this issue.  Want to make sure your tests worked correctly?

**Comment by muddeatr** [comment]
I will try a new install this asap and let you know. Thanks!!
________________________________
