### ISSUE TITLE
6.0.4 Issues - Object reference not set to an instance of an object when using an email address

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/DNN.ActiveDirectory#29]
Thanks a bunch for the help @sawest !!!

This is the first error received in testing. I am testing the login with an email address "joebags@donutzrus.com" and receive the following error. Remember now the user "joebags" is a valid user. The domain "donutzrus.com" is NOT our AD domain. So in reality this should return a regular error message for login failure.

Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Authentication.ActiveDirectory.ADSI.Utilities.UPNToLogonName0(String UserPrincipalName)
   at DotNetNuke.Authentication.ActiveDirectory.Login.get_UserName()
   at DotNetNuke.Authentication.ActiveDirectory.Login.cmdLogin_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by sawest** [comment]
We have had bad weather where I work and have been unable to get in the office for a week.  I am now back and will be working on this asap.

**Comment by sawest** [comment]
There was bug when using an invalid domain in UPN format.  That has been fixed in 6.0.6.  Please verify at your earliest convenience.

**Comment by muddeatr** [comment]
@sawest, I created a new test instance of my production site and ran the 6.0.6 install. The new test install went fine and so far testing login scenarios are going OK also. I will probably put this into my production environment tomorrow or Wed. Thanks again for all your help!!!
