### ISSUE TITLE
Issue with setup/config using Evoq Content Basic

### ISSUE THREAD

**Issue by BEhlbeck** [DNNCommunity/DNN.ActiveDirectory#34]
I am experiencing a critical error trying log in with Windows after installing and configuring this module. I am hoping to have the site setup with auto login using AD and windows authentication configured. I am running Evoq Content Basic 8.04.02. This is my first attempt at using authentication other than the default. I believe I have followed all of the steps.  

No errors when installing module, no errors when configuring module. Critical error when attempting to log in with Windows. No problem with standard login. 

When going back into the authentication settings under Extensions I am getting an error as follows and I am not able to select anything on the Authentication Type line - it is blank.

Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Authentication.ActiveDirectory.Settings.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace --- 

Any advice/direction would be appreciated.
Thanks
Beverly

Critical error when logging in is:

Message:Synchronization Error in Request: http://dnnupgrade.sechelt.ca/SynchronizeCache.aspx?message=xSr-vkVpkiDrfKuMii3ZWQ%3d%3d&data=YiybrjWiVMgrjGk_FVJLDWt4U8IrrIPt_cXBfRBzwh0%3d

StackTrace:
InnerMessage:The remote server returned an error: (401) Unauthorized.
InnerStackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at DotNetNuke.Professional.Providers.CachingProviders.WebRequestCachingProvider.WebRequestCachingProvider.OnSynchronizeResponseCallback(IAsyncResult asynchronousResult)

**Comment by sawest** [comment]
The stack shows that the problem is originating in DotNetNuke.Professional which leads me to believe that Evoq may be conflicting with the module in some way (possibly in its caching?).  I do not have Evoq and have no way to test this.

Does Evoq support windows authentication?  If you are able to initially configure this module, then get an error when returning to configure, it sounds as though a critical setting is being erased by something.  Does Evoq have any settings to turn off caching?  Would be good to see if that made a difference.

Need someone with the ability to do some Evoq testing for us.

**Comment by BEhlbeck** [comment]
Thank you - I will open a ticket directly with DNN and see if they can help.


Beverly Ehlbeck
District of Sechelt
IT Manager
Mobile: 604.740.7669

On Jan 30, 2018, at 6:37 AM, Steven A West <notifications@github.com<mailto:notifications@github.com>> wrote:


The stack shows that the problem is originating in DotNetNuke.Professional which leads me to believe that Evoq may be conflicting with the module in some way (possibly in its caching?). I do not have Evoq and have no way to test this.

Does Evoq support windows authentication? If you are able to initially configure this module, then get an error when returning to configure, it sounds as though a critical setting is being erased by something. Does Evoq have any settings to turn off caching? Would be good to see if that made a difference.

Need someone with the ability to do some Evoq testing for us.

**Comment by sawest** [comment]
Any update on this issue?

**Comment by moorecreative** [comment]
I wasn't involved in the original comment/question, but I can at least confirm for you that
- Evoq Basic 7x and 8x worked correctly with DotNetNuke Active Directory Authentication Module version 5.x
- after upgrade steps to Evoq 9.0 it worked correctly to allow login through the version 5x of the module
- after upgrade to Evoq 9.2.2 the 5.x module stopped working (login is not successful and displays "remember passwords are case sensitive" message)
- on Evoq 9.2.2 the DotNetNuke Active Directory Authentication Module version 6.x up through 7.0 has, at least in my current instance of testing, the same error. It may be an unrelated issue, but I wanted to at least document that the Authentication module up through 5x is confirmed as working on Evoq Basic up through Evoq version 9.0

**Comment by sawest** [comment]
Closing due to lack of feedback. Can reopen if more information is provided.
