### ISSUE TITLE
Extension settings don't load

### ISSUE THREAD

**Issue by hallmatt** [DNNCommunity/DNN.ActiveDirectory#64]
## Describe the bug
Upon module upgrade, I can no longer edit the extension and view/edit/update the module settings. I get a "The page cannot be displayed because an internal server error has occurred." and an exception in the Log Viewer:

```
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:590c2a3d-bf21-4c85-add6-ccccc345a758

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:P3vpriwSsFUA/0pFDC/k/A==

Message:C:\inetpub\wwwroot\site\DesktopModules\AuthenticationServices\ActiveDirectory\Settings.ascx(15): error BC30456: 'Page' is not a member of 'ASP.desktopmodules_authenticationservices_activedirectory_settings_ascx'.

StackTrace:

InnerMessage:C:\inetpub\wwwroot\site\DesktopModules\AuthenticationServices\ActiveDirectory\Settings.ascx(15): error BC30456: 'Page' is not a member of 'ASP.desktopmodules_authenticationservices_activedirectory_settings_ascx'.

InnerStackTrace:

   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.Modules.Admin.Extensions.AuthenticationEditor.get_SettingsControl()
   at DotNetNuke.Modules.Admin.Extensions.AuthenticationEditor.Initialize()
   at DotNetNuke.Modules.Admin.Extensions.EditExtension.BindData()
   at DotNetNuke.Modules.Admin.Extensions.EditExtension.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

Is there a SQL statement that needs to run in order to upgrade the PortalSettings? I upgraded from 05.00.06 to the latest release.

## Software Versions
- DNN: 07.04.01
- Module: v7.00.00

## To Reproduce
1. Go to Admin --> Extensions
2. Click the edit pencil to edit settings for "DNN_ActiveDirectoryAuthentication"
3. A plain "The page cannot be displayed because an internal server error has occurred." error appears, I don't see the settings, and the exception above appears in the Admin --> Log Viewer

I specifically am trying to enable/view the logs that are now apparently available (#54) to help debug some bigger editing issues and authenticating deep page links (ex: http://intranet.com/About/Test)

**Comment by sawest** [comment]
Is this still a problem with the newest version?

**Comment by sawest** [comment]
Closing due to inactivity and I cannot reproduce.

**Comment by hallmatt** [comment]
I haven't used DNN in like years. I could have helped at the time...but 5 years later? Not so much.

**Comment by anpa8** [comment]
I have this problem with actual version 8, compiled by myself
