### ISSUE TITLE
Unable to view/edit Site Settings

### ISSUE THREAD

**Issue by hallmatt** [DNNCommunity/DNN.ActiveDirectory#65]
## Describe the bug

I try to load the Site Settings (/Admin/Site-Settings) and get the following error:

```

Error: Dell Employee Purchase Programs is currently unavailable.
DotNetNuke.Services.Exceptions.ModuleLoadException: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\088cf42c\921e3c76\App_Web_login.ascx.ed3f9c87.0ktnw0oi.0.vb(61): 
error BC32206: The project currently contains references to more than one version of DotNetNuke, a direct reference to version 7.4.1.280 and an indirect reference (through 'DotNetNuke.Authentication.ActiveDirectory.Login') to version 8.0.4.226.
Change the direct reference to use version 8.0.4.226 (or higher) of DotNetNuke.
---> System.Web.HttpCompileException: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\088cf42c\921e3c76\App_Web_login.ascx.ed3f9c87.0ktnw0oi.0.vb(61): 
error BC32206: The project currently contains references to more than one version of DotNetNuke, a direct reference to version 7.4.1.280 and an indirect reference (through 'DotNetNuke.Authentication.ActiveDirectory.Login') to version 8.0.4.226.
Change the direct reference to use version 8.0.4.226 (or higher) of DotNetNuke.
at System.Web.Compilation.AssemblyBuilder.Compile()
 at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
 at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
 at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
 at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
 at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
 at DesktopModules.Admin.Portals.SiteSettings.<BindUserAccountSettings>b__1d(AuthenticationInfo authProvider)
 at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
 at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at DesktopModules.Admin.Portals.SiteSettings.BindUserAccountSettings(PortalInfo portal, String activeLanguage)
 at DesktopModules.Admin.Portals.SiteSettings.BindPortal(Int32 portalId, String activeLanguage)
 at DesktopModules.Admin.Portals.SiteSettings.OnLoad(EventArgs e) --- End of inner exception stack trace ---

```

Seems like the DLLs might be referencing DNN 8.x? From what I could find, it sounds like support for DNN 7.x hasn't been dropped officially - especially since there isn't a DNN 8.x requirement added in the .dnn file to utilize during install.

## Software Versions
- DNN: 07.04.01
- Module: 7.0.0

## To Reproduce
1. Go to Admin --> Site Settings
2. No settings appear - just the error message above.

## Expected behavior
I should be able to edit the site settings

**Comment by sawest** [comment]
7.0.0 install package has been updated with new 8.0.4 minimum version.
